#!/bin/sh

# Redirect output to stderr.
exec 1>&2

files="*.go cursors/*.go focus/*.go frame/*.go heads/*.go hook/*.go layout/*.go logger/*.go misc/*.go prompt/*.go render/*.go stack/*.go text/*.go wingo-cmd/*.go wini/*.go wm/*.go workspace/*.go xclient/*.go"

nofmted=$(gofmt -l $files)
if [ $(echo "$nofmted" | wc -w) != 0 ]; then
  echo "Some files are not gofmt'd:"
  for f in $nofmted; do
    echo $f
  done
  exit 1
fi

no80cols=$(colcheck $files)
if [ $(echo "$no80cols" | wc -w) != 0 ]; then
  echo "Some files do not fit in 80 columns:"
  colcheck $files
  exit 1
fi

