#!/usr/bin/env python2.7

import sys

if len(sys.argv) != 3:
    print >> sys.stderr, 'Usage: mkSData var-name data-file'
    sys.exit(1)

dname, dfile = sys.argv[1], sys.argv[2]
assembly = '''
.globl _%s
.globl _e%s
_%s:
.incbin "%s"
_e%s:
''' % (dname, dname, dname, dfile, dname)

print assembly.strip()

